# Generated by Django 2.2.15 on 2020-09-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='品牌')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='公司名称')),
                ('address', models.CharField(max_length=32, verbose_name='地址')),
                ('telphone', models.CharField(max_length=12, verbose_name='电话')),
                ('fax', models.CharField(max_length=12, verbose_name='传真')),
                ('bank', models.CharField(max_length=24, verbose_name='对公银行')),
                ('bank_no', models.CharField(max_length=24, verbose_name='银行帐号')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='公司名称')),
                ('title_en', models.CharField(max_length=64, verbose_name='公司名称英文')),
                ('address', models.CharField(max_length=32, verbose_name='地址')),
                ('telphone', models.CharField(max_length=12, verbose_name='电话')),
                ('fax', models.CharField(max_length=12, verbose_name='传真')),
                ('email', models.EmailField(max_length=24, verbose_name='邮件')),
                ('url', models.URLField(max_length=24, verbose_name='网址')),
                ('bank', models.CharField(max_length=24, verbose_name='对公银行')),
                ('bank_no', models.CharField(max_length=24, verbose_name='银行帐号')),
                ('logo', models.ImageField(upload_to='', verbose_name='LOGO')),
            ],
            options={
                'verbose_name': '甲方公司',
                'verbose_name_plural': '甲方公司',
            },
        ),
        migrations.CreateModel(
            name='contact_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=12, verbose_name='联系人')),
                ('address', models.CharField(max_length=64, verbose_name='联系地址')),
                ('phone', models.CharField(max_length=12, verbose_name='联系手机')),
                ('tel', models.CharField(max_length=12, verbose_name='联系电话')),
                ('fax', models.CharField(max_length=12, verbose_name='联系传真')),
            ],
            options={
                'verbose_name': '联系信息',
                'verbose_name_plural': '联系信息',
            },
        ),
        migrations.CreateModel(
            name='payment_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='付款方式')),
            ],
            options={
                'verbose_name': '付款方式',
                'verbose_name_plural': '付款方式',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True, verbose_name='品名规格')),
                ('nickname', models.CharField(blank=True, max_length=36, null=True, verbose_name='供应商型号')),
                ('cost_price', models.FloatField(default=0, verbose_name='产品进价')),
                ('min_selling_price', models.FloatField(default=0, verbose_name='最低售价')),
                ('meno', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '产品资料',
                'verbose_name_plural': '产品资料',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='供应商')),
                ('advantage', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='联系手机')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='单位')),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位',
            },
        ),
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='数量')),
                ('price', models.FloatField(default=0, verbose_name='单价')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('meno', models.CharField(max_length=64, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.product', verbose_name='品名规格')),
            ],
            options={
                'verbose_name': '产品明细',
                'verbose_name_plural': '产品明细',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contract.type', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.unit', verbose_name='单位'),
        ),
        migrations.CreateModel(
            name='contract_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='产品购销合同', max_length=12, verbose_name='合同名称')),
                ('contract_no', models.CharField(max_length=16, verbose_name='合同编号')),
                ('total_amount', models.FloatField(max_length=12, verbose_name='总金额')),
                ('delivery_dates', models.CharField(choices=[(0, '三个工作日内'), (1, '七个工作日内'), (2, '十个工作日内'), (3, '两周内'), (4, '四周内'), (5, '四到六周'), (6, '六到八周')], default=1, max_length=1, verbose_name='交货时间')),
                ('freight', models.CharField(choices=[(0, '甲方承担'), (1, '乙方承担'), (3, '无须运输')], default=0, max_length=1, verbose_name='运费')),
                ('delivery_Method', models.CharField(choices=[(0, '快递发货'), (1, '物流发货'), (2, '送货上门'), (3, '客户自提'), (4, '无须运输')], default=0, max_length=1, verbose_name='交货方式')),
                ('invoice_info', models.CharField(choices=[(0, '13%增值税专用发票'), (1, '6%增值税专用发票'), (2, '6%增值税普通发票'), (3, '收据')], default=0, max_length=1, verbose_name='发票税率')),
                ('add_info', models.CharField(default='打印头质保三个月或三十公里，先到为准，人为或物理损坏不在质保范围（包含但不限于打印头表面有白点、磨伤、损坏、变形、烧头等）', max_length=256, verbose_name='补充协议')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.client', verbose_name='乙方公司')),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contract.company', verbose_name='甲方公司')),
                ('payment_info', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contract.payment_info', verbose_name='付款信息')),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.product_info', verbose_name='产品明细表')),
            ],
            options={
                'verbose_name': '合同信息',
                'verbose_name_plural': '合同信息',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contact_information', verbose_name='联系人'),
        ),
    ]
