# Generated by Django 2.2 on 2020-09-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='公司名称')),
                ('title_en', models.CharField(max_length=64, verbose_name='公司名称英文')),
                ('address', models.CharField(max_length=32, verbose_name='地址')),
                ('telphone', models.CharField(max_length=12, verbose_name='电话')),
                ('fax', models.CharField(max_length=12, verbose_name='传真')),
                ('email', models.EmailField(max_length=24, verbose_name='邮件')),
                ('url', models.URLField(max_length=24, verbose_name='网址')),
                ('bank', models.CharField(max_length=24, verbose_name='对公银行')),
                ('bank_no', models.CharField(max_length=24, verbose_name='银行帐号')),
                ('logo', models.ImageField(upload_to='', verbose_name='LOGO')),
            ],
            options={
                'verbose_name': '甲方公司',
                'verbose_name_plural': '甲方公司',
            },
        ),
    ]
