# Generated by Django 2.2.15 on 2020-09-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='对公银行'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank_no',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='银行帐号'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fax',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='传真'),
        ),
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(max_length=24, unique=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bank',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='对公银行'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bank_no',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='银行帐号'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=24, null=True, verbose_name='邮件'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='LOGO'),
        ),
        migrations.AlterField(
            model_name='company',
            name='title_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='公司名称英文'),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True, max_length=24, null=True, verbose_name='网址'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='联系地址'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='fax',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='联系传真'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='tel',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='contract_info',
            name='add_info',
            field=models.CharField(blank=True, default='打印头质保三个月或三十公里，先到为准，人为或物理损坏不在质保范围（包含但不限于打印头表面有白点、磨伤、损坏、变形、烧头等）', max_length=256, null=True, verbose_name='补充协议'),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='meno',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='advantage',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='优势品牌'),
        ),
    ]
