# Generated by Django 2.2 on 2020-09-20 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20200920_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract_info',
            options={'verbose_name': '合同信息', 'verbose_name_plural': '合同信息'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品资料', 'verbose_name_plural': '产品资料'},
        ),
        migrations.AlterModelOptions(
            name='product_info',
            options={'verbose_name': '产品明细', 'verbose_name_plural': '产品明细'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
        migrations.AlterField(
            model_name='contract_info',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contract.company', verbose_name='甲方公司'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='advantage',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人'),
        ),
    ]
