# Generated by Django 2.2 on 2020-09-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20200920_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_info',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contract.company', verbose_name='甲方公司'),
        ),
    ]
